name: anatomy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  image_picker: ^0.8.4+2
  image_cropper: ^5.0.1
  flutter_zoom_drawer:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/

  fonts:
  - family: Nunito Sans
    fonts:
    - asset: assets/fonts/NunitoSans_10pt-Bold.ttf
    - asset: assets/fonts/NunitoSans_10pt-Light.ttf
    - asset: assets/fonts/NunitoSans_10pt-Medium.ttf
    - asset: assets/fonts/NunitoSans_10pt-Regular.ttf
    - asset: assets/fonts/NunitoSans_10pt-SemiBold.ttf




